on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  # release:
  #   types:
  #   - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.11.1'

    - name: Compute version numbers
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: prepare output directory
      run: |
        mkdir -p output

    - name: Create PDF files
      run: |
        chmod +x scripts/*.sh
        echo "##[section]Build Marp files to PDF"
        ls -d marp/* | xargs -I{} sh -c "echo \"##[group]Build {}\"; ./scripts/build-marp.sh {} pdf; echo \"##[endgroup]\""

    - name:
      run: |
        printenv
        for file in $(find . -maxdepth 3 -name main.pdf); do
          dir="$(dirname $file)"
          dir="$(basename $dir)"
          mv $file output/$dir-${{ env.GITVERSION_NUGETVERSIONV2 }}.pdf
        done

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: output
