on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types:
    - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.11.1'

    - name: Compute version numbers
      uses: gittools/actions/gitversion/execute@v0.9.15

    - name: prepare output directory
      run: |
        mkdir -p output

    - name: Create PDF files
      run: |
        chmod +x scripts/*.sh
        echo "##[section]Build Marp files to PDF"
        ./scripts/build-marp.sh src pdf
        mv src/*.pdf output

    - name: Upload PDF files
      uses: actions/upload-artifact@v4
      with:
        name: pdf
        path: output
