on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  # release:
  #   types:
  #   - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.11.1'

    - name: Compute version numbers
      uses: gittools/actions/gitversion/execute@v0.9.15